---

- name: create "{{ docker_dir }} "if not exists
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: create nginx reverseproxy conf
  ansible.builtin.template:
    src: docker-reverseproxy.j2
    dest: "{{ nginx_conf }}/sites-available/{{ docker_service }}.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: "enable {{ docker_service }} nginx conf"
  ansible.builtin.file:
    src: "{{ nginx_conf }}/sites-available/{{ docker_service }}.conf"
    dest: "{{ nginx_conf }}/sites-enabled/{{ docker_service }}.conf"
    owner: root
    group: www-data
    state: link
  notify: restart nginx

- name: Push docker-nginx config
  ansible.builtin.template:
    src: nginx-conf.j2
    dest: "{{ docker_dir }}/docker-nginx.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Push docker-compose.yaml
  ansible.builtin.template:
    src: nc-compose.j2
    dest: "{{ docker_dir }}/docker-compose.yaml"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Push dockerfile
  ansible.builtin.template:
    src: dockerfile.j2
    dest: "{{ dockerfile_path }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Push supervisord
  ansible.builtin.copy:
    src: supervisord.conf
    dest: "{{ docker_dir }}/supervisord.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Tear down existing "{{ docker_service }}" services
  community.general.docker_compose:
    project_name: "{{ docker_service }}"
    project_src: "{{ docker_dir }}/"
    state: absent
  register: output

- name: show debug out
  ansible.builtin.debug:
    var: output

- name: Create and start "{{ docker_service }}" services
  community.general.docker_compose:
    project_name: "{{ docker_service }}"
    project_src: "{{ docker_dir }}/"
  register: output

- name: show debug out
  ansible.builtin.debug:
    var: output
