version: '3.7'

services:
  nextcloud-db:
    container_name: nextcloud-db
    image: 'mariadb'
    user: root
    command: --transaction-isolation=READ-COMMITTED --log-bin=mysqld-bin  --binlog-format=ROW --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=1024M --innodb-log-file-size=256M --table-definition-cache=128M --tmp-table-size=128M --max-heap-table-size=128M --join-buffer-size=512K --performance-schema=1 --slow-query-log=1 --slow-query-log-file=slow.log
# --innodb_buffer_pool_size=1G --innodb_buffer_pool_instance=2 --innodb_flush_log_at_trx_commit=2 --innodb_log_buffer_size=32M
# --innodb_max_dirty_pages_pct=90
    restart: unless-stopped
    #    networks:
    #      - onlyoffice
    volumes:
      - '/data/srv/nextcloud/mysql/:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - REDIS_HOST=${REDIS_HOST}
    healthcheck:
      test: mysql --user=${MYSQL_USER} --password=${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} --execute "show tables"
      interval: "1m"
      timeout: "3s"
      start_period: "1m"
      retries: "3"

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    # user: root
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    #    networks:
    #      - onlyoffice

  app-server:
    container_name: app-server
#    image: nextcloud:fpm
    build: ./nextcloud-full
#    dockerfile: Dockerfile
    user: root
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - '80'
      - '9000'
    #    networks:
    #      - onlyoffice
    volumes:
      - '/data/srv/nextcloud/nextcloud/app_data/:/var/www/html/'
      - '/data/srv/nextcloud/supervisord/:/var/log/supervisord/'
##    environment:
##      - REDIS_HOST=nextcloud-redis
##      - REDIS_HOST_PORT=6379
#    healthcheck:
#      test: ["CMD", "curl", "--fail", "http://localhost:10005"]
#      interval: "1m"
#      timeout: "10s"
#      start_period: "1m"
#      retries: "3"
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_healthy
##      - nextcloud-redis
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    user: root
    stdin_open: true
    tty: true
    restart: unless-stopped
    #    networks:
    #      - onlyoffice
    ports:
      - '80'
      - '443'
    volumes:
      - '/data/srv/nextcloud/onlyoffice/logs:/var/log/onlyoffice'
      - '/data/srv/nextcloud/onlyoffice/data:/var/www/onlyoffice/Data'
      - '/data/srv/nextcloud/onlyoffice/lib:/var/lib/onlyoffice'
      - '/data/srv/nextcloud/onlyoffice/rabbitmq:/var/lib/rabbitmq'
      - '/data/srv/nextcloud/onlyoffice/redis:/var/lib/redis'
      - '/data/srv/nextcloud/onlyoffice/db:/var/lib/postgresql'
  #      - '/srv/nextcloud/onlyoffice/fonts:/usr/share/fonts:z'
  #      - '/srv/nextcloud/onlyoffice/core-fonts:/var/www/onlyoffice/documentserver/core-fonts:z'

  nginx-server:
    container_name: nginx-server
    image: nginx
#    user: root
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 10005:80
      - 10006:443
    #    networks:
    #      - onlyoffice
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:10005"]
      interval: "1m"
      timeout: "10s"
      start_period: "1m"
      retries: "3"
    volumes:
      - '/data/srv/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '/data/srv/nextcloud/nextcloud/app_data/:/var/www/html/'
    depends_on:
      - app-server
      - onlyoffice-document-server